branches:
  only:
    - master
language: php
php:
  - '5.6'
addons:
  ssh_known_hosts:
  - 45.55.202.78
sudo: false

# Begin Build Lifecycle
#
# 1. before_install
before_install:
  - openssl aes-256-cbc -K $encrypted_c88a8410c83d_key -iv $encrypted_c88a8410c83d_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
# 2. install
# 3. before_script
before_script:
  - composer install
# 4. script
# 5. after_success or after_failure
after_success:
  # see https://docs.travis-ci.com/user/deployment/custom/
  - chmod +x .travis/after_success.sh
  - ".travis/after_success.sh"
# 6. OPTIONAL before_deploy
# 7. OPTIONAL deploy
# 8. OPTIONAL after_deploy
# 9. after_script
